Use Sales_Co
Go

-- Q1
select EMP_NUM, EMP_FNAME,EMP_LNAME,EMP_INITIAL
from EMPLOYEE
where LOWER(EMP_LNAME) like 'smith%'
order by EMP_LNAME

-- Q2
select EMP_NUM,EMP_FNAME,EMP_LNAME,[new initial]= CONCAT(LEFT(EMP_FNAME,1),'.',LEFT(EMP_LNAME,1),'.'),EMP_YEARS
from EMPLOYEE
where EMP_YEARS >= '15' or EMP_YEARS < '5'
order by EMP_YEARS

-- Q3
select CUS_CODE,CUS_FNAME,CUS_LNAME,CUS_BALANCE
from CUSTOMER
where CUS_BALANCE > 0
order by CUS_LNAME asc, CUS_FNAME desc

-- Q4
select CUS_CODE,CUS_FNAME,CUS_LNAME,CUS_BALANCE
from CUSTOMER
where CUS_BALANCE > 0
order by CUS_LNAME asc, CUS_FNAME desc
offset 2 rows
fetch next 2 rows only

-- Q5
select INV_NUMBER,P_CODE,LINE_UNITS,LINE_PRICE,[total_amount]=LINE_UNITS*LINE_PRICE
from LINE
where INV_NUMBER NOT IN ('1003','1006','1008')

-- Q6
select top 5 INV_NUMBER,P_CODE,LINE_UNITS,LINE_PRICE,[total_amount]=LINE_UNITS*LINE_PRICE
from LINE
where INV_NUMBER NOT IN ('1003','1006','1008')

-- Q7
select INV_NUMBER,P_CODE,LINE_UNITS,LINE_PRICE,[total_amount]=LINE_UNITS*LINE_PRICE
from LINE
where LINE_UNITS*LINE_PRICE >= 25.00 AND LINE_UNITS*LINE_PRICE <= 35.00 

-- Q8
select INV_NUMBER,INV_DATE
from INVOICE
where CUS_CODE = '10014' AND INV_DATE < '2018-01-17'