---NakshathramRamyanth

use [Large_Co]
go

---Q1
SELECT CONCAT(EMP_LNAME, ', ', EMP_FNAME) AS [FULL NAME], EMP_TITLE, EMP_EMAIL
FROM DBO.LGEMPLOYEE
WHERE (YEAR(EMP_HIREDATE) = '1982' OR YEAR(EMP_HIREDATE) = '1983')
AND DEPT_NUM = 550
ORDER BY EMP_LNAME, EMP_FNAME

--- Q2
SELECT 
VENDOR.VEND_ID, VENDOR.VEND_NAME, VENDOR.VEND_CITY, VENDOR.VEND_STATE,
PRODUCT.PROD_SKU, PRODUCT.PROD_CATEGORY, PRODUCT.PROD_DESCRIPT,
BRAND.BRAND_NAME
FROM DBO.LGVENDOR VENDOR
JOIN DBO.LGSUPPLIES SUPPLIES ON VENDOR.VEND_ID = SUPPLIES.VEND_ID
JOIN DBO.LGPRODUCT PRODUCT ON SUPPLIES.PROD_SKU = PRODUCT.PROD_SKU
JOIN DBO.LGBRAND BRAND ON PRODUCT.BRAND_ID = BRAND.BRAND_ID
WHERE PRODUCT.PROD_CATEGORY LIKE '%primer%'
AND PRODUCT.PROD_PRICE > 10
AND PRODUCT.PROD_QOH <= 25
ORDER BY PRODUCT.PROD_SKU

---Q3
SELECT CUSTOMER.CUST_CODE,CUSTOMER.CUST_FNAME,CUSTOMER.CUST_LNAME,CUSTOMER.CUST_CITY,CUSTOMER.CUST_STATE,
COUNT(INVOICE.INV_NUM) AS NUMBER_OF_INVOICES
FROM dbo.LGCUSTOMER CUSTOMER
INNER JOIN DBO.LGINVOICE INVOICE ON CUSTOMER.CUST_CODE = INVOICE.CUST_CODE
WHERE CUSTOMER.CUST_STATE = 'OH'
GROUP BY CUSTOMER.CUST_CODE,CUSTOMER.CUST_FNAME,CUSTOMER.CUST_LNAME,CUSTOMER.CUST_CITY,CUSTOMER.CUST_STATE
HAVING COUNT(INVOICE.INV_NUM)>=5
ORDER BY NUMBER_OF_INVOICES DESC

---Q4
SELECT EMP_NUM,EMP_FNAME,EMP_LNAME,EMP_TITLE
FROM DBO.LGEMPLOYEE
WHERE EMP_NUM NOT IN
	(SELECT EMPLOYEE_ID FROM DBO.LGINVOICE)
ORDER BY EMP_LNAME, EMP_FNAME

---Q5
SELECT BRAND.BRAND_NAME, BRAND.BRAND_TYPE, PRODUCT.PROD_SKU, PRODUCT.PROD_DESCRIPT, CONCAT('$',PRODUCT.PROD_PRICE) as PROD_PRICE
FROM DBO.LGBRAND BRAND
JOIN DBO.LGPRODUCT PRODUCT ON BRAND.BRAND_ID = PRODUCT.BRAND_ID
WHERE BRAND.BRAND_TYPE = 'VALUE'
AND PRODUCT.PROD_PRICE >
	(SELECT AVG(PRODUCT.PROD_PRICE)
	FROM DBO.LGPRODUCT PRODUCT
	JOIN DBO.LGBRAND BRAND ON PRODUCT.BRAND_ID = BRAND.BRAND_ID
	WHERE BRAND.BRAND_TYPE = 'PREMIUM')
ORDER BY PRODUCT.PROD_PRICE DESC

---Q6
CREATE TABLE tempLGProduct (
	PROD_SKU		VARCHAR(15) PRIMARY KEY,
	PROD_DESCRIPT	VARCHAR(255) NOT NULL,
	PROD_TYPE		VARCHAR(255) NOT NULL,
	PROD_BASE		VARCHAR(255) NOT NULL,
	PROD_CATEGORY	VARCHAR(255) NOT NULL,
	PROD_PRICE		NUMERIC(10,2) CHECK (PROD_PRICE>=0),
	PROD_QOH		INT NOT NULL,
	PROD_MIN		INT NULL,
	BRAND_ID		NUMERIC(4,0) NULL,
	FOREIGN KEY (BRAND_ID) REFERENCES LGBRAND(BRAND_ID)
)

---Q7
INSERT INTO tempLGProduct VALUES ('9998-YY1', 'Traffic Paint', 'Exterior','Water','Top Coat',7.00,15,50,35);
INSERT INTO tempLGProduct VALUES ('9999-YY2', 'Primer, Non-vinyl Wash', 'Interior','Solvent','Primer',18.00,68,55,35);

---Q8
UPDATE DBO.tempLGProduct
SET PROD_BASE = 'Solvent-YY'
WHERE PROD_SKU = '9999-YY2'

---Q9
DELETE FROM DBO.tempLGProduct
WHERE PROD_SKU = '9999-YY2'

---Q10
GO
CREATE VIEW vw_ProductsByBrand
AS
SELECT BRAND.BRAND_NAME,COUNT(PROD_SKU) AS 'COUNT_OF_PRODUCTS', CONCAT('$',AVG(PROD_PRICE)) AS 'AVERAGE_PRICE' 
FROM DBO.LGBRAND BRAND
INNER JOIN DBO.LGPRODUCT PRODUCT ON BRAND.BRAND_ID=PRODUCT.BRAND_ID
GROUP BY BRAND.BRAND_NAME

SELECT * FROM vw_ProductsByBrand
GO